# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet365Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('odd', models.IntegerField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaddyPowerBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('odd', models.IntegerField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Horse')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('paddy_power_data', django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='"url" and "event_id" is required')),
                ('bet365_data', django_extensions.db.fields.json.JSONField(blank=True, default=dict)),
                ('william_hill_data', django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='"url" and "template_name" is required')),
                ('sky_bet_data', django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='"url" and "event_id" is required')),
                ('horses', models.ManyToManyField(blank=True, related_name='races', to='scraper.Horse')),
            ],
        ),
        migrations.CreateModel(
            name='SkyBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('odd', models.IntegerField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Race')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WilliamHillBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('odd', models.IntegerField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Race')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paddypowerbet',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Race'),
        ),
        migrations.AddField(
            model_name='bet365bet',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Horse'),
        ),
        migrations.AddField(
            model_name='bet365bet',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Race'),
        ),
    ]
