# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OddMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd', models.IntegerField()),
                ('probability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bet365',
            fields=[
                ('oddmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraper.OddMixin')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Race')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            bases=('scraper.oddmixin', models.Model),
        ),
        migrations.CreateModel(
            name='PaddyPowerBets',
            fields=[
                ('oddmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraper.OddMixin')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Race')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            bases=('scraper.oddmixin', models.Model),
        ),
        migrations.CreateModel(
            name='WilliamHillBets',
            fields=[
                ('oddmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraper.OddMixin')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Race')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            bases=('scraper.oddmixin', models.Model),
        ),
    ]
