# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:58
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20170703_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='bet365_data',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='race',
            name='paddy_power_data',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='race',
            name='william_hill_data',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict),
        ),
    ]
