# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:48
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20170703_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bet365',
            new_name='Bet365Bets',
        ),
        migrations.AlterField(
            model_name='race',
            name='paddy_power_data',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text=b'"url" and "event_id" is required'),
        ),
        migrations.AlterField(
            model_name='race',
            name='william_hill_data',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text=b'"url" and "template_name" is required'),
        ),
    ]
