# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20170703_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet365Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('odd', models.IntegerField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Race')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='PaddyPowerBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('odd', models.IntegerField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Race')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='WilliamHillBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('odd', models.IntegerField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Race')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.RemoveField(
            model_name='bet365bets',
            name='horse',
        ),
        migrations.RemoveField(
            model_name='bet365bets',
            name='oddmixin_ptr',
        ),
        migrations.RemoveField(
            model_name='bet365bets',
            name='race',
        ),
        migrations.RemoveField(
            model_name='paddypowerbets',
            name='horse',
        ),
        migrations.RemoveField(
            model_name='paddypowerbets',
            name='oddmixin_ptr',
        ),
        migrations.RemoveField(
            model_name='paddypowerbets',
            name='race',
        ),
        migrations.RemoveField(
            model_name='williamhillbets',
            name='horse',
        ),
        migrations.RemoveField(
            model_name='williamhillbets',
            name='oddmixin_ptr',
        ),
        migrations.RemoveField(
            model_name='williamhillbets',
            name='race',
        ),
        migrations.DeleteModel(
            name='Bet365Bets',
        ),
        migrations.DeleteModel(
            name='OddMixin',
        ),
        migrations.DeleteModel(
            name='PaddyPowerBets',
        ),
        migrations.DeleteModel(
            name='WilliamHillBets',
        ),
    ]
