# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20170703_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='horses',
            field=models.ManyToManyField(related_name='races', to='scraper.Horse'),
        ),
        migrations.AlterField(
            model_name='race',
            name='paddy_power_data',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='"url" and "event_id" is required'),
        ),
        migrations.AlterField(
            model_name='race',
            name='william_hill_data',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='"url" and "template_name" is required'),
        ),
    ]
