# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_paddypowerbet_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paddypowerbet',
            old_name='token',
            new_name='relation',
        ),
        migrations.AddField(
            model_name='bet365bet',
            name='relation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='williamhillbet',
            name='relation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
