# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20170704_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet365bet',
            old_name='relation',
            new_name='uniid',
        ),
        migrations.RenameField(
            model_name='paddypowerbet',
            old_name='relation',
            new_name='uniid',
        ),
        migrations.RenameField(
            model_name='williamhillbet',
            old_name='relation',
            new_name='uniid',
        ),
    ]
