# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20170704_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('odd', models.IntegerField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('uniid', models.CharField(blank=True, max_length=255)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Race')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
