# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:43
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_skybet'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='sky_bet',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='"url" and "event_id" is required'),
        ),
    ]
