# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_race_sky_bet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet365bet',
            name='odd',
        ),
        migrations.RemoveField(
            model_name='bet365bet',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='paddypowerbet',
            name='odd',
        ),
        migrations.RemoveField(
            model_name='paddypowerbet',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='skybet',
            name='odd',
        ),
        migrations.RemoveField(
            model_name='skybet',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='williamhillbet',
            name='odd',
        ),
        migrations.RemoveField(
            model_name='williamhillbet',
            name='probability',
        ),
    ]
