# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20170705_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet365bet',
            name='odd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet365bet',
            name='probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paddypowerbet',
            name='odd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paddypowerbet',
            name='probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skybet',
            name='odd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skybet',
            name='probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='williamhillbet',
            name='odd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='williamhillbet',
            name='probability',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
