# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_auto_20170705_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='sky_bet',
            new_name='sky_bet_data',
        ),
    ]
