# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_auto_20170705_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet365bet',
            name='uniid',
        ),
        migrations.RemoveField(
            model_name='skybet',
            name='uniid',
        ),
        migrations.RemoveField(
            model_name='williamhillbet',
            name='uniid',
        ),
    ]
